### ISSUE TITLE
Skip_nfs mentioned incorrectly in 2.8.1 documentation

### ISSUE THREAD

**Issue by WolfFlight** [ossec/ossec-docs#104]
Discovered this issue while trying to sort out my issue with nfs monitoring by OSSEC.

Posted in mailing list and got response to post issue here.

https://groups.google.com/forum/#!topic/ossec-list/ieZD7Plv3gI

per the quote from ddpbsd -- "Actually it looks like 2.8.1 was released Sept 9, 2014, and this was added Feb 13, 2015. So it's not available in 2.8.1. Please create an issue at the ossec docs github, and I'll try to mark it as such soon."

**Comment by ddpbsd** [comment]
This should be fixed in pull request #105
