### ISSUE TITLE
Document the changes to behavior in ossec/ossec-hids PR#657

### ISSUE THREAD

**Issue by reyjrar** [ossec/ossec-docs#119]
Basically, this pull request allows you to do this:

```
 <directories check_all="yes" check_perms="no">/etc</directories>
```

Which will enable all checks _except_ for the permissions checking.  The previous behavior would have left the permissions checking enabled.

**Comment by ddpbsd** [comment]
I'm a bit behind at the moment. Are these changes in the future 2.9, or are they post 2.9 changes? If they are 3.0 changes, I want to hold off, I think we'll be changing the workflow of the docs after 2.9.

**Comment by nbuuck** [comment]
@reyjrar This has been resolved in https://github.com/ossec/ossec-docs/pull/201. If you concur, please update this Issue accordingly.

**Comment by nbuuck** [comment]
@ddpbsd I think this issue can be closed, but I didn't get a response to my previous comment from the originator.
