### ISSUE TITLE
release notes update for ancient versions of MS Windows

### ISSUE THREAD

**Issue by aquerubin** [ossec/ossec-docs#126]
Reminder that the post-2.9 release notes will eventually need to mention MS Windows versions OLDER than XP will probably not be able to run the OSSEC agent:

Support dropped for older MS Windows versions.  OSSEC MS Windows agents now use the ws2_32 library for IPv6 support.  This library is not available on Windows versions older than XP (WINVER < 0x0501) such as Windows ME and Windows 2000.

**Comment by mstarks01** [comment]
Windows 2000 support has already been deprecated. I wonder if 2003 support should be removed since it is already EOL.

**Comment by aquerubin** [comment]
It's now 2019.  Anyone still running Windows XP or Server 2003 should consider a different line of work.
