### ISSUE TITLE
Bintray includes sha hashes on their download pages.

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-docs#136]
Example: https://bintray.com/ossec/ossec-hids/ossec-hids/2.9.0_beta_20151211/view#

Just a reminder to add links to those in the documentation. People can choose whichever hash they want to go with, or check multiple, or check multiple from multiple sources, or whatever suits their level of paranoia. :-)

**Comment by nbuuck** [comment]
@ddpbsd Was this issue resolved in https://github.com/ossec/ossec-docs/commit/cf41d3c9565b9e7aa264d1370879f31599f368fa?

**Comment by ddpbsd** [comment]
Yes, thank you
