### ISSUE TITLE
PGP Instructions on website show HTTP not HTTPS link for wget

### ISSUE THREAD

**Issue by axi0m** [ossec/ossec-docs#168]
Before you install any package from our project, we recommend that you verify it using our PGP key. Follow these two steps if you are not used to using gpg. You first need to import our public key:

ossec-test# wget http://ossec.github.io/files/OSSEC-PGP-KEY.asc
ossec-test# gpg –import OSSEC-PGP-KEY.asc

Should change the URL for wget to HTTPS to prevent MiTM of the PGP key potentially.

**Comment by ddpbsd** [comment]
Fixed in PR #169
