### ISSUE TITLE
Docs "Manager/Agent Installation" broken link

### ISSUE THREAD

**Issue by asantaniello** [ossec/ossec-docs#181]
On:
http://ossec.github.io/docs/manual/installation/install-source.html

The indicated checksum:
https://bintray.com/artifact/download/ossec/ossec-hids/ossec-hids-2.8.3.tar.gz.sha256

Does not appear to exist:

The requested path was not found.

**Comment by ddpbsd** [comment]
Fixed in PR #182. Thanks for the report!
