### ISSUE TITLE
Rule 5710 fire on the unwanted event "SSHD authentication failed"

### ISSUE THREAD

**Issue by Jarode01** [ossec/ossec-docs#184]
Hi,

Sorry per advance but I'm not a developper, I'm not familiar with github, and I'm not not an expert in english, but I'm full of goodwill.

```

  <rule id="5710" level="5">
    <if_sid>5700</if_sid>
    <match>illegal user|invalid user</match>
    <description>Attempt to login using a non-existent user</description>
    <group>invalid_login,authentication_failed,</group>
  </rule>

...

 <rule id="5716" level="5">
    <if_sid>5700</if_sid>
    <match>^Failed|^error: PAM: Authentication</match>
    <description>SSHD authentication failed.</description>
    <group>authentication_failed,</group>
  </rule>

...

  <rule id="5720" level="10" frequency="6">
    <if_matched_sid>5716</if_matched_sid>
    <same_source_ip />
    <description>Multiple SSHD authentication failures.</description>
    <group>authentication_failures,</group>
  </rule>
```

There's an issue with the rule 5710.
It fire when there is a login attempt using a non-existent user. That's normal. It's the designed behavior.
But it also fire on an "SSH authentication failure". That's not a desirable behavior because it prevent the rule 5716 "SSHD authentication failed." to fire and then the rule 5720 "Multiple SSHD authentication failures" to fire, so that an offender will never be blocked if he make multiple SSH authentication failure from a non existent user.

Example in my auth.log :

> Sep 20 03:42:51 server sshd[4760]: Invalid user iop from 213.202.228.66
> Sep 20 03:42:51 server sshd[4760]: input_userauth_request: invalid user ghost [preauth]
> Sep 20 03:42:52 server sshd[4760]: pam_unix(sshd:auth): check pass; user unknown
> Sep 20 03:42:52 server sshd[4760]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=213.202.228.66 
> Sep 20 03:42:54 server sshd[4760]: Failed password for invalid user ghost from 213.202.228.66 port 45313 ssh2

The key word "invalide user" is not enought restrictive in the rule 5710

Regarding my auth.log, I suggest to replace :
`<match>illegal user|invalid user</match>`
 by : 
`<match>illegal user|^Invalid user</match>`
or `<match>illegal user|: invalid user</match>`

This would make the rule 5710 to fire only on the first or second line (i.e only on a login attempt).

Thank you and sorry if you don't understand what I mean but it's very difficult for me to explain a such thing in english.

Regards.

**Comment by ddpbsd** [comment]
Looks like the current source has this:
```
<decoder name="ssh-invalid-user">
  <parent>sshd</parent>
  <prematch>^Invalid user|^Illegal user</prematch>
  <regex offset="after_prematch"> from (\S+)$</regex>
  <order>srcip</order>
</decoder>
```
