### ISSUE TITLE
Weekday should be replaced by weekdays

### ISSUE THREAD

**Issue by alosadagrande** [ossec/ossec-docs#187]
Hi all,

Seems that there is a typo in docs where tag <weekday> shows that weekday and weekend are possible values. They should be replaced in the documentation by weekdays and weekends.

PS. Already reported partially on #163

**Comment by ddpbsd** [comment]
Weekends was already correct, but weekdays has been corrected in PR 188 (https://github.com/ossec/ossec-docs/pull/188). Thanks for the report!
