### ISSUE TITLE
Is the old database of rules still available anywhere? (related to Web UI)

### ISSUE THREAD

**Issue by viktorix** [ossec/ossec-docs#199]
I know Web UI is not developed anymore, but I'm doing some work on it for our internal use. Latest events section links each rule to an old docs search page. It no longer works. Is that information still available anywhere else? Here's an example where they link:
http://ossec-docs.readthedocs.io/en/latest/search.html?q=rule-id-2502

I want to clean it up, so I'm trying to figure out if I should point it somewhere else or just remove link.

Thanks.

**Comment by ddpbsd** [comment]
It should be available in the git history, but not on the OSSEC site.
