### ISSUE TITLE
Where did the docs go?

### ISSUE THREAD

**Issue by reyjrar** [ossec/ossec-docs#289]
The old docs [at readthedocs](https://ossec-docs.readthedocs.io/en/latest/index.html#) actually have all the sections and drill downs filled in.

I keep running into missing docs that used to exist here on [the new site](https://www.ossec.net/docs/)

Compare the Syslog Output Docs
  [Old Site](https://ossec-docs.readthedocs.io/en/latest/syntax/head_ossec_config.syslog_output.html) - Has all the details
  [New Site](https://www.ossec.net/docs/syntax/head_ossec_config.syslog_output.html) - Might as well not exist

What happened to the docs? I relied on them pretty heavily, but now the officially linked docs aren't there anymore.

**Comment by ddpbsd** [comment]
It's broken. I'm not sure why, but I think it has to do with some more recent website changes. @atomicturtle might have more info. In the mean time, I've been using https://ossec-documentation.readthedocs.io/en/latest/

**Comment by ddpbsd** [comment]
Looks like everything is finally fixed.
