### ISSUE TITLE
The agent is useless without the manager

### ISSUE THREAD

**Issue by ddpbsd** [ossec/ossec-docs#86]
Be more insistent that the agent software is useless without the server side. This might be less of an issue if the Windows agent installation manual wasn't blank, but Windows users don't write documentation.

From JB, based on emails he gets from random "professionals."

**Comment by nbuuck** [comment]
@ddpbsd This appears to have been resolved in PR https://github.com/ossec/ossec-docs/pull/91, Commit https://github.com/ddpbsd/ossec-docs/commit/ec238ca66bfa6d0f51fd61330f94eb4a2b1e9c11.

**Comment by ddpbsd** [comment]
Thanks! I'm slacking..
