### ISSUE TITLE
postgresql log format needs changing on ubuntu

### ISSUE THREAD

**Issue by bobjolliffe** [ossec/ossec-docs#95]
The posgresql_log decoder expects the log_line_prefix string in postgresql.conf to be:

log_line_prefix = '[%t] %h ' 

This is not necessarily going to be the case with out of the box postgresql installs.  For example, postgresql 9.3 on ubuntu server 14.04 has:

log_line_prefix = '%t '

There is no right or wrong prefix to use, but it would be useful to indicate in the ossec documentation the prefix string which is required for ossec decoder to process.

**Comment by nbuuck** [comment]
This issue doesn't appear to be relevant any longer.

https://github.com/ossec/ossec-hids/blob/master/etc/decoder.xml#L762
https://ossec.github.io/docs/syntax/head_decoders.html
