### ISSUE TITLE
OSSEC 2.8.1 Documentation Contains >=2.9 Features

### ISSUE THREAD

**Issue by dmccarney** [ossec/ossec-docs#98]
Its somewhat confusing to find [features only available in OSSEC 2.9](http://ossec-docs.readthedocs.org/en/latest/manual/output/json-alert-log-output.html) described in the documentation for OSSEC 2.8.1.

![ossec docs](https://cloud.githubusercontent.com/assets/10408347/7433809/f9df59b2-efe9-11e4-9b70-3082fe4ab84a.png)

**Comment by ddpbsd** [comment]
The documents basically follow development. I try to mark the new stuff as such to help lessen the confusion. From there I assume everyone can pretty much figure it out. If you see something I missed, feel free to create an issue or pull request!

**Comment by dmccarney** [comment]
That's fair. Thanks for replying!
